### ISSUE TITLE
error with pip install cellyzer: Error compiling Cython file

### ISSUE THREAD

**Issue by muru-raj10** [anjuchamantha/cellyzer---CDR-data-analyzer#2]
```
Collecting cellyzer
  Using cached cellyzer-1.1.4-py3-none-any.whl (20 kB)
Collecting xlrd==1.2.0 (from cellyzer)
  Using cached xlrd-1.2.0-py2.py3-none-any.whl (103 kB)
Collecting numpy==1.18.2 (from cellyzer)
  Using cached numpy-1.18.2.zip (5.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      Running from numpy source directory.
      <string>:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      /private/var/folders/pg/42kvbdgx4_1cq1z21rfc0r8r0000gn/T/pip-install-io8tgp0a/numpy_aec4f2a0d1734d56aafd4e0c7a0304ad/tools/cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        required_version = LooseVersion('0.29.14')
      /private/var/folders/pg/42kvbdgx4_1cq1z21rfc0r8r0000gn/T/pip-install-io8tgp0a/numpy_aec4f2a0d1734d56aafd4e0c7a0304ad/tools/cythonize.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cython_version) < required_version:
      warning: _philox.pyx:19:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: /private/var/folders/pg/42kvbdgx4_1cq1z21rfc0r8r0000gn/T/pip-install-io8tgp0a/numpy_aec4f2a0d1734d56aafd4e0c7a0304ad/numpy/__init__.pxd:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  self.rng_state.ctr.v[i] = counter[i]
      
              self._reset_state_variables()
      
              self._bitgen.state = <void *>&self.rng_state
              self._bitgen.next_uint64 = &philox_uint64
                                         ^
      ------------------------------------------------------------
      
      _philox.pyx:195:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_philox.pyx
      Traceback (most recent call last):
        File "/private/var/folders/pg/42kvbdgx4_1cq1z21rfc0r8r0000gn/T/pip-install-io8tgp0a/numpy_aec4f2a0d1734d56aafd4e0c7a0304ad/tools/cythonize.py", line 238, in <module>
          main()
        File "/private/var/folders/pg/42kvbdgx4_1cq1z21rfc0r8r0000gn/T/pip-install-io8tgp0a/numpy_aec4f2a0d1734d56aafd4e0c7a0304ad/tools/cythonize.py", line 234, in main
          find_process_files(root_dir)
        File "/private/var/folders/pg/42kvbdgx4_1cq1z21rfc0r8r0000gn/T/pip-install-io8tgp0a/numpy_aec4f2a0d1734d56aafd4e0c7a0304ad/tools/cythonize.py", line 225, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/private/var/folders/pg/42kvbdgx4_1cq1z21rfc0r8r0000gn/T/pip-install-io8tgp0a/numpy_aec4f2a0d1734d56aafd4e0c7a0304ad/tools/cythonize.py", line 191, in process
          processor_function(fromfile, tofile)
        File "/private/var/folders/pg/42kvbdgx4_1cq1z21rfc0r8r0000gn/T/pip-install-io8tgp0a/numpy_aec4f2a0d1734d56aafd4e0c7a0304ad/tools/cythonize.py", line 80, in process_pyx
          subprocess.check_call(
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/mururaj/Desktop/Python/PyVenv/bin/python', '-m', 'cython', '-3', '--fast-fail', '-o', '_philox.c', '_philox.pyx']' returned non-zero exit status 1.
      Cythonizing sources
      Traceback (most recent call last):
        File "/Users/mururaj/Desktop/Python/PyVenv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/mururaj/Desktop/Python/PyVenv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/mururaj/Desktop/Python/PyVenv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/pg/42kvbdgx4_1cq1z21rfc0r8r0000gn/T/pip-build-env-o68quyod/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/pg/42kvbdgx4_1cq1z21rfc0r8r0000gn/T/pip-build-env-o68quyod/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/pg/42kvbdgx4_1cq1z21rfc0r8r0000gn/T/pip-build-env-o68quyod/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 488, in <module>
        File "<string>", line 469, in setup_package
        File "<string>", line 275, in generate_cython
      RuntimeError: Running cythonize failed!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by uuusman872** [comment]
try installing without specifying any version in setup file in install_requires
![image](https://github.com/user-attachments/assets/568b6fcf-dfc5-4c84-b294-505b30434117)
